name: Build and upload vsix artifact

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build extension vsix file
        run: |
          npm install --global @vscode/vsce
          vsce package

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: "*.vsix"
          name: "codescene-latest"