# This can be run manually to trigger either a patch, minor och major release.
# It updated the release number in package.json, updates CHANGELOG.md (the one
# you see in the vscode marketplace), tags the commit and pushes it.
#
# See also the github-release workflow.
name: Trigger release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options:
          - major
          - minor
          - patch
        default: patch
        description: Choose what to bump.


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: echo input
        run: |
          echo "bump: ${{ inputs.bump }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Bump version in package.json
        run: npm run release:${{ inputs.bump }}

      - name: Push package.json, CHANGELOG.md and tags
        run: git push --follow-tags origin main

